version: "3"
services:
  app:
    image: node:18-alpine
    restart: always
    working_dir: /app
    command: sh -c "npm i -g pnpm && pnpm install && node scripts/monitor.js"
    ports:
      - 3003:3003
    volumes:
      - .:/app